version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - '8000:80'
  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      -./src:/var/www/html/
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: nulmeting
        MYSQL_USER: yago
        MYSQL_PASSWORD: yago
    ports:
        - "9906:3306"